config/routes.rb
Rails.application.routes.draw do
  resources :games
  resources :players
  resources :tags
  resources :modifier_instances
  resources :modifiers
  resources :spaces
  resources :geographies
  resources :helpers
  resources :quests

  get 'games/next_turn/:id' => 'games#next_turn', as: :next_turn

  get 'games/discard_helper/:id/:helper_id/:player_id' => 'games#discard_helper', as: :discard_helper
  post 'games/draw_helper' => 'games#draw_helper'

  get 'games/discard_quest/:id/:quest_id/:player_id' => 'games#discard_quest', as: :discard_quest
  post 'games/draw_quest' => 'games#draw_quest'

  get 'games/start/:id' => 'games#start', as: :start_game
  post 'games/add_player' => 'games#add_player'

  post 'helpers/add_modifier' => 'helpers#add_modifier'
  post 'quests/add_modifier' => 'quests#add_modifier'

  root 'static_pages#home'

end

app/models/game.rb
class Game < ActiveRecord::Base
  has_and_belongs_to_many :players, -> {order "games_players.created_at asc"}
  #has_many :players, -> {order "games_players.created_at asc"}, join_table: :games_players
  belongs_to :current_player, class_name: "Player"

  has_and_belongs_to_many :quest_discards, join_table: :quest_discard_piles, class_name: "Quest"
  has_and_belongs_to_many :helper_discards, join_table: :helper_discard_piles, class_name: "Helper"
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy, :start, :draw_quest, :discard_quest, :draw_helper, :discard_helper, :next_turn]

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  def start
    if @game.players.count < 2
      note = "You need at least two players to start."
    else
      @game.turn = 1
      @game.current_player = @game.players.first
      @game.save
      note = "Game started!"
    end

    redirect_to @game, notice: note
  end

  def draw_quest
    player = Player.where(id: params[:player_id]).first
    geography = Geography.where(id: params[:geography_id]).first

    # Pick a quest that was not discarded
    #quests = Quest.all.where.not(id: @game.quest_discards).where(geography: geography)
    quests = Quest.where.not(id: @game.quest_discards).to_a
    @game.players.each do |p|
      quests.delete p.quest
    end

    # Reshuffle if there are no more quests left
    if quests.count == 0
      quests += @game.quest_discards.to_a
      @game.quest_discards = []
    end

    if quests.size <= 0
      note = "Not enough quest cards to choose from!"
    else
      player.quest = quests[rand(quests.size)]
      player.save
      note = "Selected quest: #{player.quest.title}"
    end

    redirect_to @game, notice: note
  end


  def draw_helper
    player = Player.where(id: params[:player_id]).first
    geography = Geography.where(id: params[:geography_id]).first

    # Pick a helper that was not discarded
    helpers = Helper.where.not(id: @game.helper_discards).where(geography: geography).to_a
    @game.players.each do |p|
      p.helpers.each do |h|
        helpers.delete h
      end
    end

    # Reshuffle if there are no more helpers left
    if helpers.count == 0
      helpers += @game.helper_discards.to_a
      @game.helper_discards = []
    end

    if helpers.size <= 0
      note = "Not enough helper cards to choose from!"
    else
      helper = helpers[rand(helpers.size)]
      player.helpers << helper
      note = "Selected helper: #{helper.title}"
    end

    redirect_to @game, notice: note
  end


  def discard_helper
    helper = Helper.where(id: params[:helper_id]).first
    player = Player.where(id: params[:player_id]).first
    play = params[:play]

    if helper and player
      if @game.helper_discards.include? helper
        note = "helper #{helper.title} is already in the discard pile!"
      else
        @game.helper_discards << helper
        player.helpers.delete helper
        player.modifier_instances += helper.modifier_instances if(play)
        note = "#{play ? 'Played' : 'Discarded'} helper #{helper.title}"
      end
    else
      note = "Could not discard helper #{params[:helper_id]} for player #{params[:player_id]}"
    end

    redirect_to @game, notice: note
  end



  def discard_quest
    quest = Quest.where(id: params[:quest_id]).first
    player = Player.where(id: params[:player_id]).first
    complete = params[:complete]

    if quest and player
      if @game.quest_discards.include? quest
        note = "Quest #{quest.title} is already in the discard pile!"
      else
        @game.quest_discards << quest
        player.quest = nil
        player.points += quest.points if(complete)
        player.save
        note = "#{complete ? 'Completed' : 'Discarded'} quest #{quest.title}"
      end
    else
      note = "Could not discard quest #{params[:quest_id]} for player #{params[:player_id]}"
    end

    redirect_to @game, notice: note
  end

  # GET /games/1/edit
  def edit
  end

  def next_turn
    players = @game.players.to_a
    p_idx = players.find_index(@game.current_player)

    if p_idx.nil?
      note = "Could not find player #{@game.current_player.name}"
    else
      n_idx = p_idx + 1
      n_player = players[n_idx]

      @game.current_player.modifier_instances = []

      # Done with all players, next turn
      if n_player.nil?
        note = "Beginning next turn"
        @game.current_player = players.first
        @game.turn += 1
        @game.save
      else
        # Next player in the same turn
        @game.current_player = n_player
        @game.save
      end
    end

    redirect_to @game, notice: note
  end

  def add_player
    @game = Game.where(id: params[:game_id]).first
    @player = Player.where(id: params[:player]).first

    if @game and @player
      @player.reset
      @game.players << @player
      note = "Successfully add player #{@player.name}"
    else
      note = "could not add player #{params[:player]} to game #{params[:game_id]}"
    end

    redirect_to edit_game_path(@game), notice: note
  end
  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { render :edit, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:name, :winner_id)
    end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<h2>Game Details</h2>
<%= render 'form' %>

<h2>Add Players</h2>
<ul>
<% @game.players.each do |p| -%>
  <li><strong><%= p.name -%></strong></li>
<%- end -%>
</ul>
<%= form_tag controller: :games, action: :add_player do %>
  <%= hidden_field_tag :game_id, @game.id %>
  <%= select_tag "player", options_from_collection_for_select(Player.all, "id", "name") %>
  <%= submit_tag "Add Player" %>
<% end %>
<%= link_to "Show Game", @game %>
<%= link_to "New Player", new_player_path %>

app/views/games/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Games</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Winner</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.name %></td>
        <td><%= game.winner_id %></td>
        <td><%= link_to 'Show', game %></td>
        <td><%= link_to 'Edit', edit_game_path(game) %></td>
        <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game', new_game_path %>

app/views/games/new.html.erb
<h1>New Game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<h1>Game <%= @game.name %></h1>
<p id="notice"><%= notice %></p>
<% if @game.turn == 0 %>
  <p><%= link_to "Start Game", start_game_path(@game) %></p>
<% else %>
  <p>
  Turn: <%= @game.turn %> - <%= @game.current_player.name %>
  <%= link_to "Next Player", next_turn_path(@game) %>
  </p>
  <% @game.players.each do |player| %>
    <%= render partial: "players/player", locals: {player:player} %>
  <% end %>
<% end %>