config/routes.rb
Rails.application.routes.draw do
  resources :games
  resources :players
  resources :tags
  resources :modifier_instances
  resources :modifiers
  resources :spaces
  resources :geographies
  resources :helpers
  resources :quests

  get 'games/next_turn/:id' => 'games#next_turn', as: :next_turn

  get 'games/discard_helper/:id/:helper_id/:player_id' => 'games#discard_helper', as: :discard_helper
  post 'games/draw_helper' => 'games#draw_helper'

  get 'games/discard_quest/:id/:quest_id/:player_id' => 'games#discard_quest', as: :discard_quest
  post 'games/draw_quest' => 'games#draw_quest'

  get 'games/start/:id' => 'games#start', as: :start_game
  post 'games/add_player' => 'games#add_player'

  post 'helpers/add_modifier' => 'helpers#add_modifier'
  post 'quests/add_modifier' => 'quests#add_modifier'

  root 'static_pages#home'

end

app/controllers/helpers_controller.rb
class HelpersController < ApplicationController
  before_action :set_helper, only: [:show, :edit, :update, :destroy]

  # GET /helpers
  # GET /helpers.json
  def index
    @helpers = Helper.all
    @good = @helpers.select{|h| h.good?}
    @bad = @helpers.select{|h| h.bad?}
    @nuetral = @helpers.select{|h| h.nuetral?}
  end

  # GET /helpers/1
  # GET /helpers/1.json
  def show
  end

  # GET /helpers/new
  def new
    @helper = Helper.new
  end

  # GET /helpers/1/edit
  def edit
  end

  def add_modifier
    mid = params[:modifier]
    gid = params[:geography]
    sid = params[:space]
    hid = params[:helper_id]
    remove = params[:remove]
    m = Modifier.where(id: mid).first
    g = Geography.where(id: gid).first
    s = Space.where(id: sid).first
    h = Helper.where(id: hid).first

    if remove
      mi = ModifierInstance.where(id: params[:modifier_instance]).first
      h.modifier_instances.delete(mi)
    end

    if m.nil?
      flash[:error] = "Could not find modifier with ID #{mid}"
    else
      if h.nil?
        flash[:error] = "Could not find helper with ID #{hid}"
      else
        mi = ModifierInstance.find_or_create_by(modifier: m, geography: g, space: s)
        h.modifier_instances << mi
      end
    end

    @helper = h
    redirect_to edit_helper_path(h)
  end

  # POST /helpers
  # POST /helpers.json
  def create
    @helper = Helper.new(helper_params)

    respond_to do |format|
      if @helper.save
        format.html { redirect_to edit_helper_path(@helper), notice: 'Helper was successfully created.' }
        format.json { render :show, status: :created, location: @helper }
      else
        format.html { render :new }
        format.json { render json: @helper.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /helpers/1
  # PATCH/PUT /helpers/1.json
  def update
    respond_to do |format|
      if @helper.update(helper_params)
        format.html { redirect_to edit_helper_path(@helper), notice: 'Helper was successfully updated.' }
        format.json { render :show, status: :ok, location: @helper }
      else
        format.html { render :edit }
        format.json { render json: @helper.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /helpers/1
  # DELETE /helpers/1.json
  def destroy
    @helper.destroy
    respond_to do |format|
      format.html { redirect_to helpers_url, notice: 'Helper was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_helper
      @helper = Helper.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def helper_params
      params.require(:helper).permit(:title, :text, :geography_id, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/geographies_helper.rb
module GeographiesHelper
end

app/helpers/helpers_helper.rb
module HelpersHelper
end

app/helpers/modifier_instances_helper.rb
module ModifierInstancesHelper
  def add_modifier_worker(params, helper_or_quest)
    mid = params[:modifier]
    gid = params[:geography]
    sid = params[:space]
    remove = params[:remove]
    m = Modifier.where(id: mid).first
    g = Geography.where(id: gid).first
    s = Space.where(id: sid).first

    if helper_or_quest.nil?
      flash[:error] = "Helper or Quest was not found."
      redirect_to(quests_path)
    end

    if remove
      mi = ModifierInstance.where(id: params[:modifier_instance]).first
      helper_or_quest.modifier_instances.delete(mi)
    end

    if m.nil?
      flash[:error] = "Could not find modifier with ID #{mid}"
    else
      mi = ModifierInstance.find_or_create_by(modifier: m, geography: g, space: s)
      helper_or_quest.modifier_instances << mi
    end
  end

end

app/helpers/modifiers_helper.rb
module ModifiersHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/quests_helper.rb
module QuestsHelper
end

app/helpers/spaces_helper.rb
module SpacesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/helpers/_form.html.erb
<%= form_for(@helper, html: {multipart: true}) do |f| %>
  <% if @helper.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@helper.errors.count, "error") %> prohibited this helper from being saved:</h2>

      <ul>
      <% @helper.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="field">
    <%= f.label :geography_id %><br>
    <%= f.select "geography_id", options_from_collection_for_select(Geography.all, "id", "name", selected: @helper.geography_id), {include_blank: 'Any'} %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/helpers/_helper.html.erb
<div class="helper_wrapper">
<div class="helper_card">
  <div class="helper_header"> 
    <div class="title"><%=helper.title%></div>
    <span class="points"><%=helper.points%></span>
  </div>
  <!--<div class="helper_picture">...</div>-->
  <div class="helper_text"><%=helper.text%></div>
  <div class="helper_modifiers">
    <% helper.modifier_instances.each do |mi| %>
      <%= mi.to_words %>
    <% end %>
  </div>
  <div class="helper_bottom" <%= helper.geography ? "style=background-color:#{helper.geography.color};color:white;" : ""%>>
    <%= helper.geography ? helper.geography.name : "Any Geography" %>
  </div>
</div>
<div class="web-only">
  <% if game.nil? %>
    <%= link_to "Edit", edit_helper_path(helper) %> | 
    <%= link_to "Delete", helper, method: :delete, data: { confirm: 'Are you sure?' } %>
  <% else %>
    <%= link_to "Play", discard_helper_path(game, helper, player, play: true) %>
    <%= link_to "Discard", discard_helper_path(game, helper, player) %>
  <% end %>
</div>
</div>

app/views/helpers/edit.html.erb
<h1>Editing Helper</h1>
<p><%= link_to "< All Helpers", helpers_path%> | <%= link_to "New Helper", new_helper_path %></p>
<div class="left">
  <%= render partial: "helper", locals: {helper:@helper, game: nil, player: nil} %>
</div>

<div class="right">
  <h2>Card Details</h2>
  <%= render 'form' %>

  <h2>Modifiers</h2>
  <ul>
    <% @helper.modifier_instances.each do |mi| %>
      <li><%= mi.to_words %> <%= link_to "Remove", {action: :add_modifier, controller: :helpers, helper_id: @helper.id, modifier_instance: mi.id, remove: true}, method: :post %></li>
      <%# mi.to_words %> <%# link_to "Remove", {action: :add_modifier, controller: :helpers, helper_id: @helper.id, modifier: mi.modifier.id, geography: mi.geography, space: mi.space, remove: true}, method: :post %>
    <% end %>
  </ul>
  <%= form_tag controller: :helpers, action: :add_modifier do %>
    <%= hidden_field_tag :helper_id, @helper.id %>
    <%= select_tag "modifier", options_from_collection_for_select(Modifier.all, "id", "name") %> in geography
    <%= select_tag "geography", options_from_collection_for_select(Geography.all, "id", "name"), {include_blank: 'Any'} %> on space
    <%= select_tag "space", options_from_collection_for_select(Space.all, "id", "name"), {include_blank: 'Any'} %>
    <%= submit_tag "Add Modifier" %>
  <% end %>
</div>

app/views/helpers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Helpers</h1>
<p><%= link_to "New Helper", new_helper_path %></p>

<h2>Balance</h2>
  Total Cards: <%= @helpers.count %>
<h3>By Helpfulness</h3>
<ul>
  <li>
  Good Cards: <%= @good.size %> (<%= (@good.size.to_f/@helpers.count.to_f * 100).round(2)%>%)
    <p><%= @good.map{|h| link_to(h.title, h)}.join(', ').html_safe %></p>
  </li>
  <li>
    Bad Cards: <%= @bad.size %> (<%= (@bad.size.to_f/@helpers.count.to_f * 100).round(2)%>%)
    <p><%= @bad.map{|h| link_to(h.title, h)}.join(', ').html_safe %></p>
  </li>
  <li>
    Nuetral Cards: <%= @nuetral.size %> (<%= (@nuetral.size.to_f/@helpers.count.to_f * 100).round(2)%>%)
    <p><%= @nuetral.map{|h| link_to(h.title, h)}.join(', ').html_safe %></p>
  </li>
</ul>
<h3>By Geography</h3>
<ul>
  <% 
    geo_l = Geography.all.to_a
    geo_l << nil
    geo_l.each do |geo| 
      geo_helpers = @helpers.select{|h| h.geography == geo}
      good = geo_helpers.select{|h| h.good?}
      bad = geo_helpers.select{|h| h.bad?}
      nuetral = geo_helpers.select{|h| h.nuetral?}
  %>
  <li>
  <%= geo ? geo.name : "No Geogrpahy" %>: <%= geo_helpers.size %> (<%= (geo_helpers.size.to_f/@helpers.count.to_f * 100).round(2)%>%) 
  <%= (good.size.to_f/geo_helpers.size.to_f * 100).round(2)%>% Good,
  <%= (bad.size.to_f/geo_helpers.size.to_f * 100).round(2)%>% Bad,
  <%= (nuetral.size.to_f/geo_helpers.size.to_f * 100).round(2)%>% Nuetral
    <p><%= geo_helpers.map{|h| link_to(h.title, h)}.join(', ').html_safe %></p>
  </li>
  <% end %>
</ul>

<h2>Cards</h2>

<% @helpers.each do |helper| %>
  <%= render partial: "helper", locals: {helper: helper, game: nil, player: nil} %>
<% end %>

app/views/helpers/new.html.erb
<h1>New Helper</h1>

<%= render 'form' %>

<%= link_to 'Back', helpers_path %>

app/views/helpers/show.html.erb
<p id="notice"><%= notice %></p>

<%= render partial: "helper", locals: {helper: @helper, game: nil, player: nil} %>