config/routes.rb
Rails.application.routes.draw do
  resources :games
  resources :players
  resources :tags
  resources :modifier_instances
  resources :modifiers
  resources :spaces
  resources :geographies
  resources :helpers
  resources :quests

  get 'games/next_turn/:id' => 'games#next_turn', as: :next_turn

  get 'games/discard_helper/:id/:helper_id/:player_id' => 'games#discard_helper', as: :discard_helper
  post 'games/draw_helper' => 'games#draw_helper'

  get 'games/discard_quest/:id/:quest_id/:player_id' => 'games#discard_quest', as: :discard_quest
  post 'games/draw_quest' => 'games#draw_quest'

  get 'games/start/:id' => 'games#start', as: :start_game
  post 'games/add_player' => 'games#add_player'

  post 'helpers/add_modifier' => 'helpers#add_modifier'
  post 'quests/add_modifier' => 'quests#add_modifier'

  root 'static_pages#home'

end

app/models/geography.rb
class Geography < ActiveRecord::Base
  has_many :spaces
end

app/controllers/geographies_controller.rb
class GeographiesController < ApplicationController
  before_action :set_geography, only: [:show, :edit, :update, :destroy]

  # GET /geographies
  # GET /geographies.json
  def index
    @geographies = Geography.all
  end

  # GET /geographies/1
  # GET /geographies/1.json
  def show
  end

  # GET /geographies/new
  def new
    @geography = Geography.new
  end

  # GET /geographies/1/edit
  def edit
  end

  # POST /geographies
  # POST /geographies.json
  def create
    @geography = Geography.new(geography_params)

    respond_to do |format|
      if @geography.save
        format.html { redirect_to @geography, notice: 'Geography was successfully created.' }
        format.json { render :show, status: :created, location: @geography }
      else
        format.html { render :new }
        format.json { render json: @geography.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /geographies/1
  # PATCH/PUT /geographies/1.json
  def update
    respond_to do |format|
      if @geography.update(geography_params)
        format.html { redirect_to @geography, notice: 'Geography was successfully updated.' }
        format.json { render :show, status: :ok, location: @geography }
      else
        format.html { render :edit }
        format.json { render json: @geography.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /geographies/1
  # DELETE /geographies/1.json
  def destroy
    @geography.destroy
    respond_to do |format|
      format.html { redirect_to geographies_url, notice: 'Geography was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_geography
      @geography = Geography.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def geography_params
      params.require(:geography).permit(:name)
    end
end

app/helpers/geographies_helper.rb
module GeographiesHelper
end

app/views/geographies/_form.html.erb
<%= form_for(@geography) do |f| %>
  <% if @geography.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@geography.errors.count, "error") %> prohibited this geography from being saved:</h2>

      <ul>
      <% @geography.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/geographies/edit.html.erb
<h1>Editing Geography</h1>

<%= render 'form' %>

<%= link_to 'Show', @geography %> |
<%= link_to 'Back', geographies_path %>

app/views/geographies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Geographies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @geographies.each do |geography| %>
      <tr>
        <td><%= geography.name %></td>
        <td><%= link_to 'Show', geography %></td>
        <td><%= link_to 'Edit', edit_geography_path(geography) %></td>
        <td><%= link_to 'Destroy', geography, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Geography', new_geography_path %>

app/views/geographies/new.html.erb
<h1>New Geography</h1>

<%= render 'form' %>

<%= link_to 'Back', geographies_path %>

app/views/geographies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @geography.name %>
</p>

<%= link_to 'Edit', edit_geography_path(@geography) %> |
<%= link_to 'Back', geographies_path %>